server:
  port: 1501
spring:
  profiles:
    active: prod
  application:
    name:
      auth

gradution-log-queue-name: admin-log-queue
gradution-log-exchange-name: admin-log-exchange
gradution-log-bind-key: admin-log-key

gradution-register-queue-name: admin-register-queue
gradution-register-exchange-name: admin-register-exchange
gradution-register-bind-key: admin-register-key

feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
