server:
  port: 1501
spring:
  profiles:
    active: dev
  application:
    name:
      auth
  datasource:
    url: jdbc:mysql://localhost:3306/gradution?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
    driver-class-name: com.mysql.jdbc.Driver

gradution-log-queue-name: admin-log-queue
gradution-log-exchange-name: admin-log-exchange
gradution-log-bind-key: admin-log-key

gradution-register-queue-name: admin-register-queue
gradution-register-exchange-name: admin-register-exchange
gradution-register-bind-key: admin-register-key

feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
