spring:
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
      config:
        server-addr: http://localhost:8848
        file-extension: yaml
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: admin
          uri: lb://admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: msg
          uri: lb://msg
          predicates:
            - Path=/msg/**
          filters:
            - StripPrefix=1
        - id: msg-websocket
          uri: ws://localhost:1324
          predicates:
            - Path=/channel/**
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:1401/auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
#    database: 0
#    host: 47.101.131.174         # Redis服务器地址
#    port: 6379              # Redis服务器连接端口
    password: requirepassgradution              # Redis服务器连接密码（默认为空）
    timeout: 10000
    lettuce:
      pool:
          max-active: 8
          max-wait: -1ms
          min-idle: 0
          max-idle: 8
      cluster:
        refresh:
          adaptive: true
      shutdown-timeout: 100
    cluster:
      nodes:
        - 106.13.17.32:6371
        - 106.13.17.32:6372
        - 106.13.17.32:6373
        - 106.13.17.32:6374
        - 106.13.17.32:6375
        - 106.13.17.32:6376
  datasource:
    url: jdbc:mysql://localhost:3306/gradution?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
    driver-class-name: com.mysql.jdbc.Driver

secure:
  ignore:
    urls:
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/channel/**"
      - "/auth/oauth/token"
      - "/auth/rsa/publicKey"
      - "/admin/login"
      - "/admin/loadByUsername"
      - "/admin/register"
      - "/admin/oss/policy"
      - "/admin/oss/callback"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details:

gradution-log-queue-name: admin-log-queue
gradution-log-exchange-name: admin-log-exchange
gradution-log-bind-key: admin-log-key

gradution-register-queue-name: admin-register-queue
gradution-register-exchange-name: admin-register-exchange
gradution-register-bind-key: admin-register-key

gradution-msg-websocket-queue-name: msg-websocket-queue
gradution-msg-websocket-exchange-name: msg-websocket-exchange
gradution-msg-websocket-bind-key: msg-websocket-key

