spring:
  profiles:
    active: prod
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5t5ooShYHhD7FimwVy3f # 访问身份验证中用到用户标识
    accessKeySecret: vvDg0IMryUgtBdJMgs2UV4k9qQxiGt # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: graution # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:1401/admin/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: image # 上传文件夹路径前缀