server:
  port: 1201
  servlet:
    context-path: /gradution
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gradution?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.37.3 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: 123456  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  rabbitmq: #rabbitmq相关配置
    host: 192.168.37.3
    port: 5672
    username: guest
    password: guest
  elasticsearch:
      rest:
        uris: 192.168.37.3:9200
#  data:
#    mongodb:
#      uri: mongodb://192.168.37.3:27017
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
jwt:
  tokenHeader: Authorization
  tokenHead: Bearer
  expiration: 3600
  secret: gradution

mybatis:
  mapper-locations:
      - classpath*:jz/cdgy/mbg/xml/*.xml
      - classpath:mybatis/*.xml
  type-aliases-package: jz/cdgy/mab/pojo
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  config: classpath:logback-spring.xml

gradution-log-queue-name: admin-log-queue
gradution-log-exchange-name: admin-log-exchange
gradution-log-bind-key: admin-log-key
#management: #开启SpringBoot Admin的监控
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always
#
#redis:
#  database: mall
#  key:
#    admin: 'ums:admin'
#  expire:
#    common: 86400 # 24小时
#aliyun:
#  oss:
#    endpoint: oss-cn-shenzhen.aliyuncs.com # oss对外服务的访问域名
#    accessKeyId: test # 访问身份验证中用到用户标识
#    accessKeySecret: test # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
#    bucketName: macro-oss # oss的存储空间
#    policy:
#      expire: 300 # 签名有效期(S)
#    maxSize: 10 # 上传文件大小(M)
#    callback: http://39.98.190.128:8080/aliyun/oss/callback # 文件上传成功后的回调地址
#    dir:
#      prefix: mall/images/ # 上传文件夹路径前缀
#minio:
#  endpoint: http://192.168.6.132:9090 #MinIO服务所在地址
#  bucketName: mall #存储桶名称
#  accessKey: minioadmin #访问的key
#  secretKey: minioadmin #访问的秘钥
#feign:
#  okhttp:
#    enabled: true
#ribbon:
#  ConnectTimeout: 3000 #服务请求连接超时时间（毫秒）
#  ReadTimeout: 3000 #服务请求处理超时时间（毫秒）